/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IProductFeatureDetailData } from './product-feature-detail.data';
import { IProductFeatureDetailProps } from './product-feature-detail.props.autogenerated';

/**
 *
 * ProductFeatureDetail component
 * @extends {React.PureComponent<IProductFeatureDetailProps<IProductFeatureDetailData>>}
 */
export default class ProductFeatureDetail extends React.PureComponent<IProductFeatureDetailProps<IProductFeatureDetailData>> {
    public render(): JSX.Element {
        const { config, resources } = this.props;

        return (
            <div className='row'>
                <h2>Config Value: {config.showText}</h2>
                <h2>Resource Value: {resources.resourceKey}</h2>
            </div>
        );
    }
}
