/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import CampaignPageContainer from '../campaign-page-container';
import { ICampaignPageContainerData } from '../campaign-page-container.data';
import {
  ICampaignPageContainerConfig,
  ICampaignPageContainerProps
} from '../campaign-page-container.props.autogenerated';

const mockData: ICampaignPageContainerData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: ICampaignPageContainerConfig = {
  showText: 'campaign-page-container'
};

const mockActions = {};

describe('CampaignPageContainer', () => {
  let moduleProps: ICampaignPageContainerProps<ICampaignPageContainerData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as ICampaignPageContainerProps<ICampaignPageContainerData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <CampaignPageContainer {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
