/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import CampaignContainer from '../campaign-container';
import { ICampaignContainerData } from '../campaign-container.data';
import {
  ICampaignContainerConfig,
  ICampaignContainerProps
} from '../campaign-container.props.autogenerated';

const mockData: ICampaignContainerData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: ICampaignContainerConfig = {
  showText: 'campaign-container'
};

const mockActions = {};

describe('CampaignContainer', () => {
  let moduleProps: ICampaignContainerProps<ICampaignContainerData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as ICampaignContainerProps<ICampaignContainerData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <CampaignContainer {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
