export const mockResources = {
    pickUpAtStoreWithLocationText: 'Pick up at a store',
    bopisSelectAStore: 'Select A Store',
    orLabel: 'OR',
    backToShopping: 'backToShopping',
    outOfStockErrorMessageHeader: 'There are some issues.',
    outOfStockErrorMessage: 'This product is no longer available. Please remove it from the bag.',
    cartTitle: 'Cart',
    emptyCartText: 'Your cart is empty.',
    failToGetCartText: 'Unable to get cart!',
    removeCartButtonText: 'Remove',
    cartRemoveButtonAriaLabel: 'Remove {productName}',
    pickUpAtStoreText: 'Pick up at a store ',
    waitingClass: 'waiting waiting-circular waiting-lg',
    decrementButtonAriaLabel: 'Press to decrease the quantity by 1',
    incrementButtonAriaLabel: 'Press to increment quantity by 1',
    inputQuantityAriaLabel: 'quantity input box aria label',
    discountStringText: 'Discount ',
    saveForLaterText: 'Move to Wishlist',
    nameOfWishlist: 'My Wishlist',
    productDimensionTypeColor: 'Color',
    productDimensionTypeSize: 'Size',
    productDimensionTypeStyle: 'Style',
    productDimensionTypeConfiguration: 'Configuration',
    shipInsteadDisplayText: 'Ship this item',
    changeStoreDisplayText: 'Change store',
    quantityDisplayText: 'Quantity',
    shipToAddressDisplayText: 'Ship to an address',
    pickItUpDisplayText: 'Pick this up',
    totalSavingsText: 'Savings',
    minInventoryMessage: 'There is only {0} product left. Please choose quantity',
    originalPriceText: 'Original price',
    currentPriceText: 'Current price',
    cartLoadingErrorMessage: 'Sorry we are unable to load your cart at this moment, please try again later.',
    orderSummaryTitle: 'Order summary',
    itemsWithCountLabel: 'Subtotal ',
    estimatedShippingLabel: 'Estimated Shipping',
    priceFree: 'Free',
    estimatedTaxLabel: 'Estimated Tax',
    totalAmountLabel: 'Amount due ',
    totalSavings: 'Total savings ',
    conditionsText: '*Before applicable taxes',
    yetToBeCalculatedText: 'To be calculated',
    orderTotal: 'Order total',
    notApplicationForCartOrderSummary: 'Not applicable',
    totalDiscountsLabel: 'Total discounts',
    guestCheckoutButtonTitle: 'Guest Checkout',
    checkoutButtonTitle: 'Checkout',
    backToShoppingButtonTitle: 'Back to shopping',
    addToWishlistButtonText: 'Move to wishlist',
    removeFromWishlistButtonText: 'Remove from wishlist',
    defaultWishlistName: 'My Wishlist',
    promoCodeHeadingText: 'Promo code',
    promoPlaceholderText:'Enter a promo code',
    promoCodeApplyButtonText: 'Apply',
    removePromoAriaLabelFormat: '{0} {1}',
    removePromoText: 'Remove',
    appliedPromoCodeHeadingText: 'Applied promo code',
    invalidPromoCodeErrorText: 'Invalid promo code',
    failedToAddPromoCodeErrorText: 'Failed to add promo code',
    failedToRemovePromoCodeErrorText: 'Failed to remove promo code',
    duplicatePromotionErrorText: 'Promo code already applied'
};