/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { ISampleButtonData } from './sample-button.data';
import { ISampleButtonProps } from './sample-button.props.autogenerated';
import { SampleStateInput } from '../../actions/sample-state';

/**
 *
 * SampleButton component
 * @extends {React.PureComponent<ISampleButtonProps<ISampleButtonData>>}
 */
export default class SampleButton extends React.PureComponent<ISampleButtonProps<ISampleButtonData>> {
    public render(): JSX.Element {
        // const { config, resources } = this.props;

        return <button onClick={this._onClick}>Click Me!</button>;
    }

    // OnClick Handler should update application state
    private _onClick = (e: React.MouseEvent): void => {
        console.log('click count ', this.props.data.sampleState.result);
        if (this.props.data.sampleState.result) {
            // This will directly update our application state, which should trigger all modules observing the state to update
            this.props.context.actionContext.update(new SampleStateInput(), {
                clickCount: this.props.data.sampleState.result.clickCount + 1
            });
        }
    };
}
